global using Domain.Events;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using UserProfile.Domain.UserProfiles.ValueObjects;
global using UserProfile.Application.Contracts;
global using Application.CQRS;
global using UserProfile.Application.Dtos;
global using UserProfile.Application.Exceptions;
global using AutoMapper;
global using Application.Pagination;
global using UserProfile.Application.Specification;
global using Userprofile = UserProfile.Domain.UserProfiles.UserProfile;