namespace UserProfile.Application.UserProfiles.Queries.GetFollowingInstructorsById;

public record GetFollowingInstructorsByIdQuery(StudentPaginationRequest StudentRequest) : IQuery<GetFollowingInstructorsByIdResult>;
public record GetFollowingInstructorsByIdResult(PaginatedResult<UserProfileDto> UserProfiles);
